### ISSUE TITLE
Failing specs

### ISSUE THREAD

**Issue by chikamichi** [UJKhokhar/bloccit#11]
Hey,

When I run `rspec spec`, I have two failures reported:

```
Failures:

  1) FavoritesController#create creates a favorite for the current user and specified post
     Failure/Error: post :create, { post_id: @post_id }
     ActionController::UrlGenerationError:
       No route matches {:action=>"create", :controller=>"favorites", :post_id=>nil}
     # ./spec/controllers/favorites_controller_spec.rb:18:in `block (3 levels) in <top (required)>'

  2) FavoritesController#destroy destroys the favorite for the current user and post
     Failure/Error: delete :destroy, { post_id: @post.id, id: favorite_id }
     NameError:
       undefined local variable or method `favorite_id' for #<RSpec::ExampleGroups::FavoritesController::Destroy:0x007f986200a8c8>
     # ./spec/controllers/favorites_controller_spec.rb:29:in `block (3 levels) in <top (required)>'

Finished in 0.74671 seconds (files took 2.16 seconds to load)
23 examples, 2 failures, 3 pending

Failed examples:

rspec ./spec/controllers/favorites_controller_spec.rb:15 # FavoritesController#create creates a favorite for the current user and specified post
rspec ./spec/controllers/favorites_controller_spec.rb:25 # FavoritesController#destroy destroys the favorite for the current user and post
```

Those are easily fixed.

Be sure to run `rspec spec` before pushing to GitHub (and to fix any broken spec), this is a good habit!

**Comment by chikamichi** [comment]
You may be interested in [Guard](https://github.com/guard/guard), and its plugin [Guard RSpec](https://github.com/guard/guard-rspec). It basically monitors your application, so that when you edit a model, a controller… and/or the matching spec(s), the specs automatically run again. Not necessarily something you want to install and use now, but that could be a great tool for the projects.

**Comment by UJKhokhar** [comment]
Two failures fixed here https://github.com/UJKhokhar/bloccit/commit/e6c1afab351154139ac401475a2272286015c5bb
